= Kadalu Storage Cluster

Identify a node where Storage manager will be deployed. The node can be one of the storage nodes or it can be a spare node that is highly available.

Enable and start the `kadalu-mgr`

[source,console]
----
[root@server1 ~]# systemctl enable kadalu-mgr
[root@server1 ~]# systemctl start kadalu-mgr
----

[source,console]
----
[root@server1 ~]# kadalu cluster create mycluster
Cluster created successfully.
ID: 4e67989e-0c24-44ac-b0a7-81aa5cb4ec6b
----

The cluster data and the configurations stored in `/var/lib/kadalu`. Since the storage manager is running in single node, high availability is not available for the Cluster data. It is possible to provide high availability by using `kadalu-lite` Volume or backing up the Cluster data in regular interval. Refer "High availability" chapter for more details.

Storage manager can support multiple Clusters. Use `set-default` to avoid typing Cluster name or ID with every command.

[source,console]
----
[root@server1 ~]# kadalu cluster set-default mycluster
----

`set-default` is available only as a local option. On that node it remembers the default cluster.

Before inviting new nodes to the Cluster, start the `kadalu-agent` service.

[source,console]
----
[root@server2 ~]# systemctl enable kadalu-agent
[root@server2 ~]# systemctl start kadalu-agent
----

Invite new nodes to be part of the Cluster. Once it becomes the part of the Cluster, it listens to the requests from Storage manager.

[source,console]
----
[root@server1 ~]# kadalu node join -c mycluster server2.example.com
----

- `server1.example.com` should be reachable from the node where the join command is run.
- Storage manager node should be reachable from the `server1.example.com` to push the metrics.

Run `node list` to view the list of the nodes and the status.

[source,console]
----
[root@server1 ~]# kadalu node list
----
