name: Run on every PR

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'extras/**'
      - '**.md'
      - '**.adoc'

jobs:
  # TODO: Add unit test as well here
  fmt_and_lint:
    name: Code Format and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Crystal
        run: |
          curl -fsSL https://crystal-lang.org/install.sh | sudo bash
      - name: Format Check
        run: make fmt
      - name: Lint
        run: make lint
