name: Run on every PR

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'extras/**'
      - '**.md'
      - '**.adoc'

jobs:
  # TODO: Add unit test as well here
  tests:
    name: Kadalu Storage Tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Crystal
        run: |
          curl -fsSL https://crystal-lang.org/install.sh | sudo bash
      - name: Format Check
        run: make fmt-check
      - name: Lint
        run: make lint
      - name: Test Volgen
        run: |
          cd volgen && shards install && crystal spec
      - name: Install Binnacle
        run: |
          curl -L https://github.com/kadalu/binnacle/releases/latest/download/binnacle -o binnacle
          chmod +x ./binnacle
          sudo mv ./binnacle /usr/local/bin/binnacle
          binnacle --version
      - name: Build Storage node container
        run: |
          cd tests && ./build-container.sh
      - name: Setup Test environment
        run: binnacle -vv tests/setup.t
      - name: Build and Install Storage manager to nodes/containers
        run: VERSION="${{ github.ref_name }}" binnacle -vv tests/install.t
      - name: Run all Tests
        run: binnacle -vv tests/all
